application: devfest-de
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.well-known/acme-challenge/.*
  script: letsencrypt.app

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always

libraries:
- name: webapp2
  version: '2.5.2'
